/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserRegisterDto {
  email?: string | null;
  name?: string | null;
  password?: string | null;
  surname?: string | null;
}
