/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserMeDto } from '../../models/user-me-dto';

export interface Me$Json$Params {
}

export function me$Json(http: HttpClient, rootUrl: string, params?: Me$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<UserMeDto>> {
  const rb = new RequestBuilder(rootUrl, me$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserMeDto>;
    })
  );
}

me$Json.PATH = '/api/Users/me';
