/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SeasonCountDto } from '../../models/season-count-dto';

export interface GetSeasonsCount$Plain$Params {
}

export function getSeasonsCount$Plain(http: HttpClient, rootUrl: string, params?: GetSeasonsCount$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<SeasonCountDto>> {
  const rb = new RequestBuilder(rootUrl, getSeasonsCount$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SeasonCountDto>;
    })
  );
}

getSeasonsCount$Plain.PATH = '/api/Seasons/count';
