/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RainLog } from '../../models/rain-log';

export interface FindBySeason$Json$Params {
  seasonName?: string;
}

export function findBySeason$Json(http: HttpClient, rootUrl: string, params?: FindBySeason$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RainLog>>> {
  const rb = new RequestBuilder(rootUrl, findBySeason$Json.PATH, 'get');
  if (params) {
    rb.query('seasonName', params.seasonName, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<RainLog>>;
    })
  );
}

findBySeason$Json.PATH = '/api/Rain/season';
