/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SeasonLitersDto } from '../../models/season-liters-dto';

export interface SeasonLiters$Json$Params {
  seasonName?: string;
}

export function seasonLiters$Json(http: HttpClient, rootUrl: string, params?: SeasonLiters$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<SeasonLitersDto>> {
  const rb = new RequestBuilder(rootUrl, seasonLiters$Json.PATH, 'get');
  if (params) {
    rb.query('seasonName', params.seasonName, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SeasonLitersDto>;
    })
  );
}

seasonLiters$Json.PATH = '/api/Rain/seasonLiters';
