/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { FindBySeason$Plain$Params as FindBySeason$Plain$Params } from './fn/rain/find-by-season-plain';
export { findBySeason$Plain as findBySeason$Plain } from './fn/rain/find-by-season-plain';
export type { FindBySeason$Json$Params as FindBySeason$Json$Params } from './fn/rain/find-by-season-json';
export { findBySeason$Json as findBySeason$Json } from './fn/rain/find-by-season-json';
export type { NewRainLog$Plain$Params as NewRainLog$Plain$Params } from './fn/rain/new-rain-log-plain';
export { newRainLog$Plain as newRainLog$Plain } from './fn/rain/new-rain-log-plain';
export type { NewRainLog$Json$Params as NewRainLog$Json$Params } from './fn/rain/new-rain-log-json';
export { newRainLog$Json as newRainLog$Json } from './fn/rain/new-rain-log-json';
export type { DeleteRainLog$Plain$Params as DeleteRainLog$Plain$Params } from './fn/rain/delete-rain-log-plain';
export { deleteRainLog$Plain as deleteRainLog$Plain } from './fn/rain/delete-rain-log-plain';
export type { DeleteRainLog$Json$Params as DeleteRainLog$Json$Params } from './fn/rain/delete-rain-log-json';
export { deleteRainLog$Json as deleteRainLog$Json } from './fn/rain/delete-rain-log-json';
export type { SeasonLiters$Plain$Params as SeasonLiters$Plain$Params } from './fn/rain/season-liters-plain';
export { seasonLiters$Plain as seasonLiters$Plain } from './fn/rain/season-liters-plain';
export type { SeasonLiters$Json$Params as SeasonLiters$Json$Params } from './fn/rain/season-liters-json';
export { seasonLiters$Json as seasonLiters$Json } from './fn/rain/season-liters-json';
export type { GetAllSeasons$Plain$Params as GetAllSeasons$Plain$Params } from './fn/seasons/get-all-seasons-plain';
export { getAllSeasons$Plain as getAllSeasons$Plain } from './fn/seasons/get-all-seasons-plain';
export type { GetAllSeasons$Json$Params as GetAllSeasons$Json$Params } from './fn/seasons/get-all-seasons-json';
export { getAllSeasons$Json as getAllSeasons$Json } from './fn/seasons/get-all-seasons-json';
export type { AddSeason$Params as AddSeason$Params } from './fn/seasons/add-season';
export { addSeason as addSeason } from './fn/seasons/add-season';
export type { GetSeasonsCount$Plain$Params as GetSeasonsCount$Plain$Params } from './fn/seasons/get-seasons-count-plain';
export { getSeasonsCount$Plain as getSeasonsCount$Plain } from './fn/seasons/get-seasons-count-plain';
export type { GetSeasonsCount$Json$Params as GetSeasonsCount$Json$Params } from './fn/seasons/get-seasons-count-json';
export { getSeasonsCount$Json as getSeasonsCount$Json } from './fn/seasons/get-seasons-count-json';
export type { Register$Params as Register$Params } from './fn/users/register';
export { register as register } from './fn/users/register';
export type { Login$Plain$Params as Login$Plain$Params } from './fn/users/login-plain';
export { login$Plain as login$Plain } from './fn/users/login-plain';
export type { Login$Json$Params as Login$Json$Params } from './fn/users/login-json';
export { login$Json as login$Json } from './fn/users/login-json';
export type { Me$Plain$Params as Me$Plain$Params } from './fn/users/me-plain';
export { me$Plain as me$Plain } from './fn/users/me-plain';
export type { Me$Json$Params as Me$Json$Params } from './fn/users/me-json';
export { me$Json as me$Json } from './fn/users/me-json';
